//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SperanskiyAkzamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategorii_tovara
    {
        public int code { get; set; }
        public string name_categoriya_tovara { get; set; }
    }
}
