//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SperanskiyAkzamen
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Bd_SperanskiyEntities : DbContext
    {
        private static Bd_SperanskiyEntities _context;
        public Bd_SperanskiyEntities()
            : base("name=Bd_SperanskiyEntities")
        {
        }
        public static Bd_SperanskiyEntities GetContext()
        {
            if (_context == null)
                _context = new Bd_SperanskiyEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public object TOVAR { get; internal set; }
    }
}

